version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    command: >
      sh -c "python init_db.py && gunicorn --bind 0.0.0.0:8000 --workers 4 --timeout 120 app:app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    volumes:
      - ./webapp:/app/webapp
      - ./backend:/app/backend
      - ./licencia:/app/licencia
    restart: unless-stopped


  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: orange_user
      POSTGRES_PASSWORD: orange_pass
      POSTGRES_DB: orange_poliza
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: "orange-poliza-engine-copia_postgres_data"
    external: true

